newPRWelcomeComment: >
  This is your first PR! Thanks and welcome! Don't forget to check out our [CONTRIBUTING.md](https://github.com/jooaodanieel/GCommit/blob/master/CONTRIBUTING.md) guidelines :blue_heart:
